src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class GuestForm(forms.Form):
    email    = forms.EmailField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class RegisterForm(forms.Form):
    username = forms.CharField()
    email    = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password2 != password:
            raise forms.ValidationError("Passwords must match.")
        return data


src/addresses/forms.py
from django import forms

from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            #'billing_profile',
            #'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            'state',
            'postal_code'
        ]


src/ecommerce/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class ContactForm(forms.Form):
    fullname = forms.CharField(
            widget=forms.TextInput(
                    attrs={
                        "class": "form-control", 
                        "placeholder": "Your full name"
                    }
                    )
            )
    email    = forms.EmailField(
            widget=forms.EmailInput(
                    attrs={
                        "class": "form-control", 
                        "placeholder": "Your email"
                    }
                    )
            )
    content  = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class': 'form-control',
                    "placeholder": "Your message" 
                    }
                )
            )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not "gmail.com" in email:
            raise forms.ValidationError("Email has to be gmail.com")
        return email
















src/ecommerce/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.http import HttpResponse
from django.shortcuts import render,redirect

from .forms import ContactForm

def home_page(request):
    # print(request.session.get("first_name", "Unknown"))
    # request.session['first_name']
    context = {
        "title":"Hello World!",
        "content":" Welcome to the homepage.",

    }
    if request.user.is_authenticated():
        context["premium_content"] = "YEAHHHHHH"
    return render(request, "home_page.html", context)

def about_page(request):
    context = {
        "title":"About Page",
        "content":" Welcome to the about page."
    }
    return render(request, "home_page.html", context)

def contact_page(request):
    contact_form = ContactForm(request.POST or None)
    context = {
        "title":"Contact",
        "content":" Welcome to the contact page.",
        "form": contact_form,
    }
    if contact_form.is_valid():
        print(contact_form.cleaned_data)
    # if request.method == "POST":
    #     #print(request.POST)
    #     print(request.POST.get('fullname'))
    #     print(request.POST.get('email'))
    #     print(request.POST.get('content'))
    return render(request, "contact/view.html", context)





def home_page_old(request):
    html_ = """
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      </head>
      <body>
        <div class='text-center'>
            <h1>Hello, world!</h1>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
      </body>
    </html>
    """
    return HttpResponse(html_)



src/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Base Template</title>
        {% include 'base/css.html' %}
        {% block base_head %}{% endblock %}
    </head>
    <body>
      {% include 'base/navbar.html' with brand_name='eCommerce' %}
      <div class='container'>
      {% block content %}{% endblock %}
    </div>



        {% include 'base/js.html' %}
    </body>
  </html>

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!-- Fontawesome CSS -->
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    {% if brand_name %} {{brand_name }} {% else %}CFE eCommerce {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>


      {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>

       <!--  <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->

    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>

src/templates/bootstrap/example.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>


<nav class="navbar navbar-expand-md navbar-dark bg-dark">
   <div class='container'>
      <a class="navbar-brand" href="#">
        <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
        Bootstrap
      </a>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarCollapseLinks' aria-expanded='false' aria-label='Toggle Navigation'>
        <span class='navbar-toggler-icon'></span>
      </button>




      <div class='collapse navbar-collapse' id='navbarCollapseLinks'>
        <ul class='navbar-nav'>
          <li class='nav-item'>
            <a href='#' class='nav-link'>Home</a>
          </li>
          <li class='nav-item'>
            <a href='#' class='nav-link'>About</a>
          </li>
          <li class='nav-item'>
            <a href='#' class='nav-link'>Products</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>

        </ul>


        <form class="form-inline ml-auto">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
  </div>
</nav>






    <div class='container'>
        <div class='row'>
            <div class='col-12'>
                <div class="alert alert-secondary" role="alert">
                Nav
                </div>
            </div>

        </div>

        <div class='row mb-3'>

          <div class='col-12 col-sm-12 col-md-6 col-lg-4 ml-auto'>
            <input type='text' class='form-control' placeholder="Search">
          </div>

        </div>
        <div class='row'>
            <div class='col-11 mx-auto col-lg-2 order-12'>
                <div class="alert alert-primary" role="alert">
                Bottom Content Item
                </div>
            </div>
            <div class='col-11 col-lg-8 mx-auto order-6' >
                <div class="alert alert-primary" role="alert" style='min-height: 800px;'>
                Middle

                <div class='row'>
                  <div class='col-8'>
                      <div class="alert alert-primary" role="alert">
                      This is a primary alert—check it out!
                      </div>
                  </div>
                  <div class='col-4'>
                      <div class="alert alert-secondary" role="alert">
                      This is a primary alert—check it out!
                      </div>
                  </div>

                </div>
                <div class='row'>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                 
            </div>



                </div>
            </div>
            <div class='col-12 col-lg-2 order-1'>
                <div class="alert alert-secondary" role="alert">
                Top Content Item
                </div>
            </div>

        </div>


    </div>








    <div class='container'>
            <div class='row'>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                 
            </div>

    </div>
    <div class='container-fluid'>
        <div class='row'>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                <div class='col-1'>
                    <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                    </div>
                </div>
                
            </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/contact/view.html
{% extends "base.html" %}


{% block content %}
<div class='text-center'>
          <h1>{{ title }}</h1>
          <h1>Hello, world we're working!</h1>
      </div>
      <div class='container'>
      <div class='row'>
        <div class='col'>
            <p>{{ content }}</p>
            <div class='col-sm-6 col-12'>
            <form method='POST'> {% csrf_token %}
              {{ form.as_p }}
              <button type='submit' class='btn btn-default'>Submit</button>
            </form>


            <!-- <form method='POST'> {% csrf_token %}
              <input type='text' class='form-control' placeholder="Name" name='fullname'>
              <input type='email' class='form-control' placeholder="Email" name='email'>
              <textarea name='content' class='form-control' placeholder="Your content"></textarea>
              <button type='submit' class='btn btn-default'>Submit</button>
            </form> -->
            </div>
        </div>
      </div>
      </div>
{% endblock %}

src/templates/home_page.html
{% extends "base.html" %}
{% load static %}

<title>Home Page Template</title>

{% block base_head %}
<link rel='stylesheet' href='{% static "css/main.css" %}' >
{% endblock %}

{% block content %}
<div class='text-center'>
    <h1>{{ title }}</h1>
    <h1>Hello, world we're working!</h1>
</div>

<div class='row'>
  <div class='col'>
      <img src="{% static 'img/beach.jpg' %}" class='img-fluid' />
      <p>{{ content }}</p>
  </div>
</div>
{% if request.user.is_authenticated %}
<div class='row'>
  <div class='col'>
  <h1>Premium</h1>
  {{ premium_content }}
  </div>
</div>
{% endif %}


{% endblock %}

<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <link rel='stylesheet' href='{% static "css/main.css" %}' >
    </head>
    <body>
      <div class='text-center'>
          <h1>{{ title }}</h1>
          <h1>Hello, world we're working!</h1>
      </div>
      <div class='container'>
        <div class='row'>
          <div class='col'>
              <img src="{% static 'img/beach.jpg' %}" class='img-fluid' />
              <p>{{ content }}</p>
          </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class='row'>
          <div class='col'>
          <h1>Premium</h1>
          {{ premium_content }}
          </div>
        </div>
        {% endif %}
      </div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
  </html>